defmodule CrywolfWeb.PageController do
  use CrywolfWeb, :controller

  plug :set_honeybadger_context

  def index(conn, _params) do
    render conn, "index.html"
  end

  def key_error(conn, _params) do
    conn.foo
  end

  def async_error(conn, _params) do
    Task.start fn ->
      Honeybadger.context %{test: "value", more: "data"}
      raise "Oh no!"
    end
    conn
  end

  def runtime_error(conn, _params) do
    raise RuntimeError, message: "This is a runtime error generated by the crywolf app."
  end

  defp set_honeybadger_context(conn, _opts) do
    Honeybadger.context(user_id: 100000, account_id: 5)
    conn
  end
end
