defmodule Crywolf.PageController do
  use Crywolf.Web, :controller
  use Honeybadger.Plug

  def index(conn, _params) do
    render conn, "index.html"
  end

  def key_error(conn, _params) do
    conn.foo
  end

  def runtime_error(conn, _params) do
    raise RuntimeError, message: "This is a runtime error generated by the crywolf app."
  end
end
